---
version: "3.9"
services:
  prowlarr:
    image: hotio/prowlarr:release-1.29.2.4915@sha256:7e4e4c4439280e414455c7b9a0e76ac0e11d0e13716c1bfc0aaba9d2ef79a088
    container_name: prowlarr
    depends_on:
      - transmission
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - ./test.sh:/scripts/test.sh
      - ./config.xml:/config/config.xml
    ports:
      - 9696:9696
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9696/system/status"]
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 9091:9091